<ProjectPopup>:
    title: 'Projects'
    size_hint: None, None
    size: app.root.width/1.1, app.root.height/1.1
    BoxLayout:
        ProjectSelector:
            orientation: 'horizontal'
            size_hint_y: None
            height: 30

        TextInput:
            id: project_title
            size_hint_y: None
            height: 30
            hint_text: '//Project Title'


           # TODO: Build out color loading and color selection!


