<MenuBar>:
    id: menubar
    orientation: 'horizontal'
    size_hint_y: None
    padding: 0
    height: 30

    Button:
        id: new_task_button

        text: "New Task"
        on_press: root.create_new_task(*args)

    Button:
        text: 'Tasks'
        on_press: root.switch_screens('tasks', 'right')
    Button:
        text: 'Timer'
        on_press: root.switch_screens('timer', 'up')
    Button:
        text: "Stats"
        on_press: root.switch_screens('stats', 'left')